server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
    # swaagger 설정 변경
    # http://localhost:8002/eplaton/swagger-ui.html
    pathmatch:
      matching-strategy: ant-path-matcher

  security:
    user:
      name: user
      password: 1234    
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ecommerce_db?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/ecommerce_db?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: ecommerce
    password: ecommerce1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      

cos:
  key: cos1234
  
mybatis:
  #type-aliases-package: ojc.board.business.repository.entity
  #mapper-locations: classpath:mybatis/mapper/*.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
